version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hrms
      POSTGRES_PASSWORD: hrmspassword
      POSTGRES_DB: hrmsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
