name: CD - Build & Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # ✅ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ✅ Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ✅ Build & Push HRMS Backend Image
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/hrms-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/hrms-service:${{ github.sha }}

    # ✅ Logout from DockerHub
    - name: Docker Logout
      run: docker logout
